//common
import FuelBarrel from '../../images/hardwareImages/FuelBarrel.png'
import CarJack from '../../images/hardwareImages/CarJack.png'
import Radio from '../../images/hardwareImages/Radio.png'
import RS1Ruby from '../../images/hardwareImages/RS1Ruby.png'
import R1Breese from '../../images/hardwareImages/R1Breese.png'
// rare 
import FuelTank from '../../images/hardwareImages/FuelTank.png'
import RD1Listener from '../../images/hardwareImages/RD1Listener.png'
import TS1Horizon from '../../images/hardwareImages/TS1Horizon.png'
import BigG from '../../images/hardwareImages/BigG.png'
import Blastoff from '../../images/hardwareImages/Blastoff.png'
import R2Chill from '../../images/hardwareImages/R2Chill.png'
import CSTaymyr from '../../images/hardwareImages/CSTaymyr.png'
import AmmoPack from '../../images/hardwareImages/AmmoPack.png'
//special
import Chameleon from '../../images/hardwareImages/Chameleon.png'
import KA1Discharger from '../../images/hardwareImages/KA1Discharger.png'
import OculusVI from '../../images/hardwareImages/OculusVI.png'
import Maxwell from '../../images/hardwareImages/Maxwell.png'
import PU1Charge from '../../images/hardwareImages/PU1Charge.png'
import Ampere from '../../images/hardwareImages/Ampere.png'
import Hardcore from '../../images/hardwareImages/Hardcore.png'
import Razorback from '../../images/hardwareImages/Razorback.png'
import DunHorse from '../../images/hardwareImages/DunHorse.png'
import Genesis from '../../images/hardwareImages/Genesis.png'
//epic
import Tormentor from '../../images/hardwareImages/Tormentor.png'
import ChameleonMk2 from '../../images/hardwareImages/ChameleonMk2.png'
import KA2Flywheel from '../../images/hardwareImages/KA2Flywheel.png'
import RD2Keen from '../../images/hardwareImages/RD2Keen.png'
import Neutrino from '../../images/hardwareImages/Neutrino.png'
import Gasgen from '../../images/hardwareImages/Gasgen.png'
import Oppressor from '../../images/hardwareImages/Oppressor.png'
import HotRed from '../../images/hardwareImages/HotRed.png'
import HoColossustRed from '../../images/hardwareImages/Colossus.png'
import Cheetah from '../../images/hardwareImages/Cheetah.png'
import Hermes from '../../images/hardwareImages/Hermes.png'
import RNSeal from '../../images/hardwareImages/RNSeal.png'
import Shiver from '../../images/hardwareImages/Shiver.png'
import ExpandedAmmoPack from '../../images/hardwareImages/ExpandedAmmoPack.png'


